# -------------------------------------------------
# PXE Packages
# -------------------------------------------------
pxe_packages:
  - dhcp-server
  - httpd
  - syslinux
  - syslinux-tftpboot
  - tftp-server



# -------------------------------------------------
# PXE Boot Menu
# -------------------------------------------------
pxe_menu_title: "Install AlmaLinux 8 (PXE)"

pxe_grub_default: 0
pxe_grub_timeout: 0

pxe_kernel_path: "iso-data/vmlinuz"
pxe_initrd_path: "iso-data/initrd.img"

pxe_repo_url: "http://{{ pxe_server_ip }}/iso-data"
pxe_ks_url: "http://{{ pxe_server_ip }}/ks.cfg"

pxe_ip_method: dhcp
pxe_extra_kernel_args: "text"

# -------------------------------------------------
# Kickstart Selection
# -------------------------------------------------
ks_type: "lvm"   # options: standard | lvm

# -------------------------------------------------
# Kickstart Repository URLs
# -------------------------------------------------
ks_baseos_url: "http://{{ pxe_server_ip }}/iso-data/BaseOS/"
ks_appstream_url: "http://{{ pxe_server_ip }}/iso-data/AppStream/"
ks_partition_url: "http://{{ pxe_server_ip }}/partition.cfg"

# -------------------------------------------------
# Localization
# -------------------------------------------------
ks_keyboard: us
ks_lang: en_IN.UTF-8
ks_timezone: Asia/Kolkata

# -------------------------------------------------
# Network (Kickstart)
# -------------------------------------------------
ks_bootproto: dhcp

# -------------------------------------------------
# Security
# -------------------------------------------------
ks_root_password: root

# -------------------------------------------------
# Bootloader
# -------------------------------------------------
ks_bootloader_location: mbr
ks_bootloader_args: "crashkernel=auto"

# -------------------------------------------------
# Software Selection
# -------------------------------------------------
ks_environment: server-product-environment

ks_extra_packages:
  - bash-completion
  - bind-utils
  - curl
  - kexec-tools
  - lsof
  - nano
  - net-tools
  - rsync
  - sysstat
  - tar
  - unzip
  - vim
  - wget
  - zip


