---
# tasks file for docker-repo

- name: Ensure /etc/yum.repos.d directory exists
  ansible.builtin.file:
    path: /etc/yum.repos.d
    state: directory
    mode: '0755'

- name: Check if existing Docker repo file exists
  ansible.builtin.stat:
    path: /etc/yum.repos.d/docker-ce.repo
  register: docker_repo_file

- name: Backup existing Docker repo if present
  ansible.builtin.copy:
    src: /etc/yum.repos.d/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo.bk
    remote_src: yes
  when: docker_repo_file.stat.exists

- name: Download or replace Docker repo file
  ansible.builtin.get_url:
    url: "{{ docker_repo_url }}"
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '0644'
    force: yes
    validate_certs: yes

- name: Disable Docker Edge & Test repos if they exist
  ansible.builtin.ini_file:
    dest: /etc/yum.repos.d/docker-ce.repo
    section: "{{ item }}"
    option: enabled
    value: 0
  loop:
    - docker-ce-test
    - docker-ce-edge
  ignore_errors: yes  # in case those sections don't exist

