---
- name: Configure SlurmDBD
  hosts: all
  become: true

  vars_files:
    - ../../../group_vars/all.yml

  vars:
    slurmdbd_host: localhost
    slurmdbd_port: 6819

    slurmdb_storage_host: localhost
    slurmdb_storage_loc: slurm_acct_db
    slurmdb_storage_user: slurm
    slurmdb_storage_pass: "{{ vault_slurmdb_password }}"

  roles:
    - "{{ roles_parent_path }}/scheduler_lib/scheduler_slurmdbd"
