---
- name: Detect RHEL version
  ansible.builtin.set_fact:
    rhel_major_version: "{{ ansible_distribution_major_version | int }}"

- name: Include repo setup
  ansible.builtin.include_tasks: repos.yml

- name: Include installation tasks
  ansible.builtin.include_tasks: install.yml

- name: Manage PCS/DRBD services
  ansible.builtin.include_tasks: services.yml
  when: pcs_manage_services
