---
- name: Install and Configure lustre client packages on lustre client nodes
  hosts: all
  become: true
  vars_files:
    - ../../group_vars/all.yml
  vars:
    kernel_rpm_src: "{{ rpm_stack_path }}/kernel_rpms"
    lustre_conf_src: "{{ configuration_dir_path }}/lustre_client/"
    lustre_conf_dest: "/etc/modprobe.d/"
    lustre_rpm_src: "{{ configuration_dir_path }}/lustre_client"

  roles:
    - "{{ roles_parent_path }}/storage_lib/storage_lustre_client"
