---
- name: Configure DRBD replication setup
  hosts: all
  become: yes
  vars_files:
    - ../../group_vars/all.yml

  vars:
    drbd_resource_name: rudra_drbd
    drbd_disk: /dev/nvme0n1p3
    drbd_device: /dev/drbd0
    drbd_force_md_create: true
    drbd_nodes:
      - { name: "cn06", ip: "172.10.3.6" }
      - { name: "cn28", ip: "172.10.3.28" }

  roles:
    - "{{ roles_parent_path }}/storage_lib/storage_drbd_config"
