---
- name: Monitoring baseline ALL
  hosts: all
  become: yes
  vars_files:
    - ../../group_vars/all.yml

  vars:
    rsyslog_mode: "server"              #Change to client/server for specic mode config
    rsyslog_server_ip: "{{ monitoring_log_server_ip }}"


  roles:
    - "{{ roles_parent_path }}/monitoring_lib/monitoring_rsyslog"
