---
# MariaDB
slurmdb_mysql_service: mariadb

# Slurm accounting DB
slurmdb_name: slurm_acct_db
slurmdb_user: slurm
slurmdb_password: some_pass      # âš  override in vault/group_vars

slurmdb_readonly_user: readonly
slurmdb_readonly_password: some_pass

# InnoDB tuning
innodb_buffer_pool_size: 32768M
innodb_log_file_size: 64M
innodb_lock_wait_timeout: 900
