---
- name: Install Docker Compose on all nodes
  hosts: all
  become: true
  vars_files:
    - ../../../group_vars/all.yml
  vars:
    docker_compose_version: "v2.40.1"
  roles:
    - "{{ roles_parent_path }}/container_lib/docker_compose"
