---
- name: Clone hosted RPM repositories to client
  hosts: all
  become: yes
  vars_files:
    - ../../group_vars/all.yml


  vars:
    repo_server: "http://{{headnode_ip}}:8080"
    clone_dest: "{{openchai_vault_path}}/"
    download_tool: "wget"

  roles:
    - "{{ roles_parent_path }}/utility_lib/utility_repo_clone"
