---
# defaults file for xcat_container_lib
# Default variables for Docker Swarm label assignment

# Common label key-value to assign to master nodes
swarm_label_key: xcat_master
swarm_label_value: true

# List of master hostnames (must match inventory hostnames)
swarm_master_nodes:
  - "{{ primary_swarm_manager }}"
  - "{{ secondary_swarm_manager }}"

xcat_version: "2.17.0"
xCAT_reg_path: "{{ hpcsuite_registry_mount_path }}/container_img_reg/xCAT_reg"
xcat_image: "cdac_xcat/alma8.9:2.17.0"
