# vars/main.yml

# Package lists for RHEL 9
pcs_drbd_packages_rhel9:
  - pcs
  - kmod-drbd9x
  - drbd9x-utils

conflicting_drbd_pkg_rhel9:
  - drbd-utils

# Package lists for RHEL 8
pcs_drbd_packages_rhel8:
  - pcs
  - kmod-drbd84
  - drbd84-utils
conflicting_drbd_pkg_rhel8:
  - drbd-utils
